### ISSUE TITLE
"cleverbot" pypi name

### ISSUE THREAD

**Issue by folz** [edwardslabs/cleverwrap.py#5]
Hi there, I wrote https://pypi.python.org/pypi/cleverbot back when there was no official API. Would you be interested in taking over the `cleverbot` package name on pypi with your API wrapper?

**Comment by edwardslabs** [comment]
Hey there I really appreciate the offer. I definitely used your cleverbot package for quite a while before the official API was released. I don't really know of a clean way to rename a python package so that folks who have already installed cleverwrap would continue to receive updates. I am fine keeping the package named the way it is.

Thanks again!

**Comment by folz** [comment]
You're welcome! In that case, I'm marking cleverbot.py as unmaintained and pointing folks to your cleverwrap. Have a good one :)
